### ISSUE TITLE
[bug] 회원가입 시 비정상적인 이메일 전송 가능

### ISSUE THREAD

**Issue by facewise** [Cherish-Gift/cherish-gift.github.io#84]
![image](https://user-images.githubusercontent.com/62998666/231139979-a3a8a3a3-f37e-4b2a-a3fe-1d6d4b0cbb59.png)

이메일 validation 정규식을 다시 검토해봐야 할듯 합니다

**Comment by BadaHertz52** [comment]
> ![image](https://user-images.githubusercontent.com/62998666/231139979-a3a8a3a3-f37e-4b2a-a3fe-1d6d4b0cbb59.png)
> 
> 이메일 validation 정규식을 다시 검토해봐야 할듯 합니다

prettier 적용되면서 정규식에서 역슬래시가 사라져서 오류가 났습니다. 해당 오류 수정헤서 main으로 pr 날렸습니다.
